version: 1
stages:
  - name: headers
    parser: cpp
    directory: include
    files:
      - "**/*.hpp"
    steps:
      - name: generated headers
        directory: .codegen/include
        templates:
          - templates/generated.hpp.inja
          - templates/generated.inl.inja
        condition:
          type: attribute
          value:
            enabled: true