name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get -qq update &&
          sudo apt-get install -y build-essential libtbb-dev ninja-build
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh &&
          chmod u+x llvm.sh &&
          sudo ./llvm.sh 20 all &&
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-20 100 &&
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-20 100 &&
          echo /usr/lib/llvm-20 >> $GITHUB_PATH
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'a74164519874e4671e9e496444148df1d7f5006c'
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          testPreset: 'ninja-vcpkg-test-release'
      - name: Run Project Binary
        run: .cmake/ninja-vcpkg/spore-codegen-example
